// ConditionalRunPanel.jsx — PRD §5 two-run controlled comparison.
// Reads the latest runs/two_runs_*.json from /runs/ (served by Vite
// from frontend/public/) and renders a side-by-side summary.

import { useI18n } from '../i18n.jsx'

function evidenceRef(txHash, simulationId) {
  if (txHash) return `${txHash.slice(0, 18)}…`
  if (simulationId) return `offline · ${simulationId.slice(0, 14)}…`
  return '—'
}

function Card({ tone, title, badge, rows }) {
  const palette = {
    emerald: 'border-emerald-200 bg-emerald-50',
    rose: 'border-rose-200 bg-rose-50',
    sky: 'border-blue-200 bg-blue-50',
  }[tone]
  return (
    <div className={`border ${palette} rounded-xl p-4`}>
      <div className="flex items-center justify-between mb-3">
        <div className="text-sm font-semibold text-[#1d1d1f]">{title}</div>
        {badge && (
          <span className={`text-[10px] px-2 py-0.5 rounded-full uppercase tracking-wider ${badge.cls}`}>
            {badge.label}
          </span>
        )}
      </div>
      <dl className="space-y-1.5 text-xs font-mono">
        {rows.map((r) => (
          <div key={r.k} className="flex justify-between gap-3">
            <dt className="text-slate-500">{r.k}</dt>
            <dd className={`text-right break-all ${r.danger ? 'text-rose-700' : 'text-[#1d1d1f]'}`}>
              {r.v}
            </dd>
          </div>
        ))}
      </dl>
    </div>
  )
}

export default function ConditionalRunPanel({ latestRuns }) {
  const { t } = useI18n()
  const runs = latestRuns?.runs ?? []
  if (runs.length === 0) {
    return (
      <section className="surface-card border border-black/10 rounded-xl p-4">
        <h2 className="text-sm uppercase tracking-wider text-slate-500 mb-2">
          <i className="fa fa-clone mr-2"></i> {t('demo.cond.title')}
        </h2>
        <div className="text-sm text-slate-500 italic">
          {t('demo.cond.empty')}
        </div>
      </section>
    )
  }

  return (
    <section className="surface-card border border-black/10 rounded-xl p-4">
      <h2 className="text-sm uppercase tracking-wider text-slate-500 mb-3">
        <i className="fa fa-clone mr-2"></i> {t('demo.cond.title')}
      </h2>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {runs.slice(0, 2).map((r, i) => {
          const tones = ['sky', 'rose']
          const tripCodes = (r.verdict_codes || []).join(', ') || '—'
          const badge = r.verdict_level === 'TRIP'
            ? { label: `TRIP · ${r.verdict_source}`, cls: 'bg-rose-500/20 border border-rose-500/40 text-rose-700' }
            : { label: r.verdict_level, cls: 'bg-slate-100 text-slate-700' }
          return (
            <Card
              key={r.passport_id ?? i}
              tone={tones[i % tones.length]}
              title={r.label}
              badge={badge}
              rows={[
                { k: 'notional', v: `${r.spec.notionalUsd} USD` },
                { k: 'max loss', v: `${r.spec.maxLossUsd} USD` },
                { k: 'drawdown @ TRIP', v: `${r.drawdown_usd} USD`, danger: true },
                { k: 'reason codes', v: tripCodes },
                { k: 'mint evidence', v: evidenceRef(r.mint_tx_hash, r.simulation_id) },
                { k: 'revoke tx', v: evidenceRef(r.revoke_tx_hash, null) },
                { k: 'status', v: r.status },
              ]}
            />
          )
        })}
      </div>
      <div className="mt-3 text-[11px] text-slate-500">
        Generated by <code>scripts/two_runs_demo.py</code>. Offline evidence is labelled and never presented as a public-chain transaction.
      </div>
    </section>
  )
}
