// ConditionalRunPanel.jsx — PRD §5 two-run controlled comparison.
// Reads the latest runs/two_runs_*.json from /runs/ (served by Vite
// from frontend/public/) and renders a side-by-side summary.

import { useEffect, useState } from 'react'
import { useI18n } from '../i18n.jsx'

const POLL_MS = 5000

function Card({ tone, title, badge, rows }) {
  const palette = {
    emerald: 'border-emerald-700/60 bg-emerald-900/10',
    rose: 'border-rose-700/60 bg-rose-900/10',
    sky: 'border-sky-700/60 bg-sky-900/10',
  }[tone]
  return (
    <div className={`border ${palette} rounded-xl p-4`}>
      <div className="flex items-center justify-between mb-3">
        <div className="text-sm font-semibold text-slate-100">{title}</div>
        {badge && (
          <span className={`text-[10px] px-2 py-0.5 rounded-full uppercase tracking-wider ${badge.cls}`}>
            {badge.label}
          </span>
        )}
      </div>
      <dl className="space-y-1.5 text-xs font-mono">
        {rows.map((r) => (
          <div key={r.k} className="flex justify-between gap-3">
            <dt className="text-slate-400">{r.k}</dt>
            <dd className={`text-right break-all ${r.danger ? 'text-rose-300' : 'text-slate-100'}`}>
              {r.v}
            </dd>
          </div>
        ))}
      </dl>
    </div>
  )
}

export default function ConditionalRunPanel({ latestRuns }) {
  const { t } = useI18n()
  const runs = latestRuns?.runs ?? []
  if (runs.length === 0) {
    return (
      <section className="bg-slate-900/50 border border-slate-800 rounded-xl p-4">
        <h2 className="text-sm uppercase tracking-wider text-slate-400 mb-2">
          <i className="fa fa-clone mr-2"></i> {t('demo.cond.title')}
        </h2>
        <div className="text-sm text-slate-500 italic">
          {t('demo.cond.empty')}
        </div>
      </section>
    )
  }

  return (
    <section className="bg-slate-900/50 border border-slate-800 rounded-xl p-4">
      <h2 className="text-sm uppercase tracking-wider text-slate-400 mb-3">
        <i className="fa fa-clone mr-2"></i> {t('demo.cond.title')}
      </h2>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {runs.slice(0, 2).map((r, i) => {
          const tones = ['sky', 'rose']
          const tripCodes = (r.verdict_codes || []).join(', ') || '—'
          const badge = r.verdict_level === 'TRIP'
            ? { label: `TRIP · ${r.verdict_source}`, cls: 'bg-rose-500/20 border border-rose-500/40 text-rose-200' }
            : { label: r.verdict_level, cls: 'bg-slate-700 text-slate-300' }
          return (
            <Card
              key={r.passport_id ?? i}
              tone={tones[i % tones.length]}
              title={r.label}
              badge={badge}
              rows={[
                { k: 'notional', v: `${r.spec.notionalUsd} USD` },
                { k: 'max loss', v: `${r.spec.maxLossUsd} USD` },
                { k: 'drawdown @ TRIP', v: `${r.drawdown_usd} USD`, danger: true },
                { k: 'reason codes', v: tripCodes },
                { k: 'mint tx', v: r.mint_tx_hash?.slice(0, 18) + '…' },
                { k: 'revoke tx', v: r.revoke_tx_hash ? r.revoke_tx_hash.slice(0, 18) + '…' : '—' },
                { k: 'status', v: r.status },
              ]}
            />
          )
        })}
      </div>
      <div className="mt-3 text-[11px] text-slate-500">
        Generated by <code>scripts/two_runs_demo.py</code>. Both runs share the same Kiln mock and rule gate; only notional/maxLoss change.
      </div>
    </section>
  )
}